# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: true
  # Raise an error if more than 50 warnings are generated
  max-warnings: 1
# Rule Configuration
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  empty-line-between-blocks: 0
  leading-zero: 2
  no-color-keywords: 2
  no-color-literals: 2
  final-newline: 2
  placeholder-in-extend: 2
  no-trailing-whitespace: 0
  property-sort-order: 0
  no-warn: 2
  no-debug: 2
  no-ids: 2
  no-important: 2
  variable-for-property: 2
  hex-notation: 2
  space-after-color: 2
  single-line-per-selector: 2
  force-pseudo-nesting: 2
  nesting-depth:
    - 2
    -
      max-depth: 4
  indentation:
    - 2
    -
      size: 4